pinboard:
  # https://pinboard.in/settings/password
  apitoken:
instances:
  # https://tools.splat.soy/pleroma-access-token
- accesstoken:
  instanceurl: https://compostintraining.club
  deletebookmarks: true
